# Generated by Django 3.2.25 on 2024-12-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('api_token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_charges', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('disk', models.IntegerField(blank=True, null=True)),
                ('main_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('vcpu_count', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_bandwidth', models.IntegerField(blank=True, null=True)),
                ('netmask_v4', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_v4', models.CharField(blank=True, max_length=255, null=True)),
                ('power_status', models.CharField(blank=True, max_length=255, null=True)),
                ('server_status', models.CharField(blank=True, max_length=255, null=True)),
                ('v6_network', models.CharField(blank=True, max_length=255, null=True)),
                ('v6_main_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('v6_network_size', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('kvm', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('os_id', models.IntegerField(blank=True, null=True)),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('firewall_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.CharField(blank=True, max_length=255, null=True)),
                ('user_scheme', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_charges', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
            },
        ),
    ]
