# Generated by Django 3.2.25 on 2024-12-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('type_name', models.IntegerField(choices=[(0, 'Server'), (1, 'Vultr')], default=0, verbose_name='类型')),
                ('api_token', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Token')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='余额')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('pending_charges', models.FloatField(blank=True, null=True, verbose_name='待处理账单')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='上次付款时间')),
                ('last_payment_amount', models.FloatField(blank=True, null=True, verbose_name='上次支付金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('min_spent_monthly', models.FloatField(default=0, verbose_name='月度最低消费')),
            ],
            options={
                'verbose_name': '账号',
                'verbose_name_plural': '账号',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='编号')),
                ('os', models.CharField(blank=True, max_length=255, null=True, verbose_name='系统')),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='内存')),
                ('disk', models.IntegerField(blank=True, null=True, verbose_name='磁盘')),
                ('main_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IPv4')),
                ('vcpu_count', models.IntegerField(blank=True, null=True, verbose_name='vCPU')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区')),
                ('plan', models.CharField(blank=True, max_length=255, null=True, verbose_name='购买套餐')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='状态')),
                ('allowed_bandwidth', models.IntegerField(blank=True, null=True, verbose_name='每月带宽')),
                ('netmask_v4', models.CharField(blank=True, max_length=255, null=True, verbose_name='IPv4掩码')),
                ('gateway_v4', models.CharField(blank=True, max_length=255, null=True, verbose_name='IPv4网关')),
                ('power_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='电源状态')),
                ('server_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务器状态')),
                ('v6_network', models.CharField(blank=True, max_length=255, null=True, verbose_name='IPv6网络')),
                ('v6_main_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IPv6地址')),
                ('v6_network_size', models.IntegerField(blank=True, null=True, verbose_name='IPv6网络规模')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('internal_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='内网IP')),
                ('kvm', models.CharField(blank=True, max_length=255, null=True, verbose_name='KVM')),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机名')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签列表')),
                ('os_id', models.IntegerField(blank=True, null=True, verbose_name='OS ID')),
                ('app_id', models.IntegerField(blank=True, null=True, verbose_name='App ID')),
                ('image_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image ID')),
                ('firewall_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firewall GID')),
                ('features', models.CharField(blank=True, max_length=255, null=True, verbose_name='特性列表')),
                ('user_scheme', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户权限')),
                ('pending_charges', models.FloatField(blank=True, null=True, verbose_name='待处理的账单')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
            options={
                'verbose_name': '服务器实例',
                'verbose_name_plural': '服务器实例',
            },
        ),
    ]
